---
- name: sync time
  shell: ntpdate {{ ntp_server }}

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: restart zabbix-agent2
  service: 
    name: zabbix-agent2
    state: restarted
