---
# tasks file for java
- name: Extract jdk-8u231-linux-x64.tar.gz into /usr/local/
  ansible.builtin.unarchive:
    src: jdk-8u231-linux-x64.tar.gz
    dest: /usr/local/

- name: link java
  file:
    src: /usr/local/jdk1.8.0_231
    dest: /usr/local/java
    state: link

# Set JAVA_HOME
- name: ensure /etc/profile.d exists
  become: yes
  file:
    path: /etc/profile.d
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: export JAVA_HOME and add to PATH
  become: yes
  template:
    src: java.sh.j2
    dest: /etc/profile.d/java.sh
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: test java version
  ansible.builtin.shell: java -version
